---
AWSTemplateFormatVersion: '2010-09-09'
Description: Sample CloudFormation template

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0f5ee92e2d63afc18
      InstanceType: t2.micro
      KeyName: tfm
      SecurityGroups:
        - default