---
AWSTemplateFormatVersion: '2010-09-09'
Description: Sample CloudFormation template
Parameters:
  MyKey:
    Description: key Parameters
    Type: AWS::EC2::KeyPair::KeyName
  MyInstanceType:
    Description: Instance type Parameters
    Type: String
    AllowedValues:
      - t2.micro
      - t2.medium
      - m1.small
      - m1.large
    Default: t2.micro


Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0f5ee92e2d63afc18
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKey
      SecurityGroupIds:
        - default
        - !Ref MySG
  
  MySG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

      
      
